CRB_URL = 'http://www.cbr.ru/scripts/XML_daily.asp?date_req={}'
DATE_FORMAT_INPUT = '%Y-%m-%d'
DATE_FORMAT_OUTPUT = '%d/%m/%Y'
TAG_ROOT = './/Valute'
CODE_VALUTE_XML = 'CharCode'
NAME_VALUTE_XML = 'Name'
VALUE_VALUTE_XML = 'Value'
